image: golang:1.13

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

variables:
  GORELEASER_IMAGE: goreleaser/goreleaser:latest

before_script:
  - export VERSION=$(perl -ne 'print if /(?<=##\s)\d+\.\d+\.\d+/' CHANGELOG.md | awk 'NR==1 {print $2}')

# unit_tests:
#   stage: test:unit
#   script:
#     - make test

lint_code:
  stage: test
  script:
    - go get -u golang.org/x/lint/golint
    - make lint

build:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  script:
    - docker pull $GORELEASER_IMAGE
    - docker run --rm --privileged -v $PWD:/go/src/gitlab.com/thesoy_sauce/htbctl -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/gitlab.com/thesoy_sauce/htbctl -e GITLAB_TOKEN $GORELEASER_IMAGE release --rm-dist --release-notes=CHANGELOG.md
  only:
    - tags